project_id = "kxlglvjazzuarhofophh"

[functions.ai-recommendations]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.delete-account]
verify_jwt = false

[functions.send-retention-emails]
verify_jwt = false

[functions.get-users-email-status]
verify_jwt = false

[functions.resend-verification-email]
verify_jwt = false

[functions.check-verified-badge]
verify_jwt = false
